# Generated by Django 5.1.4 on 2025-01-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_author_remove_book_published_date_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default='2000-01-11'),
            preserve_default=False,
        ),
    ]
