name: Django Tests with MySQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: praveen
          MYSQL_DATABASE: inventory
          MYSQL_USER: praveen
          MYSQL_PASSWORD: praveen
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Django database settings for MySQL
        run: |
          sed -i "s|'ENGINE': 'django.db.backends.sqlite3'|'ENGINE': 'django.db.backends.mysql'|" myproject/settings.py
          sed -i "s|'NAME': BASE_DIR / 'db.sqlite3'|'NAME': 'inventory'|" myproject/settings.py
          sed -i "s|'USER': ''|'USER': 'praveen'|" myproject/settings.py
          sed -i "s|'PASSWORD': ''|'PASSWORD': 'praveen'|" myproject/settings.py
          sed -i "s|'HOST': 'localhost'|'HOST': 'localhost'|" myproject/settings.py
          sed -i "s|'PORT': '3306'|'PORT': '3306'|" myproject/settings.py


      - name: Wait for MySQL to be ready
        run: |
          until mysql -h 127.0.0.1 -u praveen -ppraveen -e "SELECT 1" inventory; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done
          
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run pytest
        run: |
          pytest
